name: adotai
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  flutter_masked_text2: ^0.9.1
  http: ^0.13.3
  flutter_launcher_icons: ^0.14.3
  image_picker: 1.0.7
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1

  
flutter_launcher_icons:
  image_path: assets/images/small-logo.png
  ios: true
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "#0099DD"
  adaptive_icon_foreground: assets/images/small-logo.png


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/adotai.png
    - assets/images/default_icon.png
